config/routes.rb
Rails.application.routes.draw do
  resources :units
  resources :homes
  resources :service_particulars
  resources :leave_records
  resources :loans
  resources :investments
  resources :posting_records
  resources :medical_cats
  resources :personel_details do
    member do
      get '/edit_more_details' => 'personel_details#edit_more_details'
      post '/update_more_details' => 'personel_details#update_more_details'
    end
  end
  resources :profiles, only: [:index, :show] do
    member do
      get '/embodiment_report' => 'profiles#embodiment_report'
      get '/embodiment_report_pdf' => 'profiles#embodiment_report', as: :embodiment_pdf_report
    end
  end
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/landing' => 'homes#landing_page'
  get '/directorate' => 'homes#directorate'
  get '/policies' => 'homes#policies'
  get '/faq' => 'homes#faq'
  get '/galary' => 'homes#galary'
  get '/news' => 'homes#news'
  get '/on_leave_index' => "homes#on_leave_index"
  get '/on_field_index' => "homes#on_field_index"
  get '/on_field_index' => "homes#on_field_index"
  get '/investments_index' => "homes#investments_index"
  get '/achievements_index' => "homes#achievements_index"

  get '/dashboard' => "homes#index"
  root to: "homes#landing_page"
  
end

app/models/medical_cat.rb
class MedicalCat < ApplicationRecord
    has_paper_trail
    belongs_to :professional_detail
    has_many :hospital_admission_histories, dependent: :destroy

    accepts_nested_attributes_for :hospital_admission_histories
    rails_admin do
        create do 
            field :professional_detail_id, :enum do
                enum do
                    ProfessionalDetail.all.collect {|p| [p.user.army_no, p.id]}
                end
            end
            field :date
            field :nature_of_emergency
            field :permanent
            field :period_year
            field :period_month
            field :hospitalized
            
            field :shape , :enum do
                enum do
                    MasterShape.all.collect{ |p| [p.title, p.title]}
                end
            end
        end

        edit do
            field :professional_detail_id, :enum do
                enum do
                    ProfessionalDetail.all.collect {|p| [p.user.army_no, p.id]}
                end
            end
            field :date
            field :nature_of_emergency
            field :permanent
            field :period_year
            field :period_month
            field :hospitalized

            field :shape , :enum do
                enum do
                    MasterShape.all.collect{ |p| [p.title, p.title]}
                end
            end
        end
    end
end

app/controllers/medical_cats_controller.rb
class MedicalCatsController < ApplicationController
  before_action :set_medical_cat, only: [:show, :edit, :update, :destroy]

  # GET /medical_cats
  # GET /medical_cats.json
  def index
    @medical_cats = MedicalCat.all
    @medical_cat = MedicalCat.new
  end

  # GET /medical_cats/1
  # GET /medical_cats/1.json
  def show
  end

  # GET /medical_cats/new
  def new
    @medical_cat = MedicalCat.new
  end

  # GET /medical_cats/1/edit
  def edit
  end

  # POST /medical_cats
  # POST /medical_cats.json
  def create
    @medical_cat = MedicalCat.new(medical_cat_params)

    respond_to do |format|
      if @medical_cat.save
        format.html { redirect_to @medical_cat, notice: 'Medical cat was successfully created.' }
        format.json { render :show, status: :created, location: @medical_cat }
      else
        format.html { render :new }
        format.json { render json: @medical_cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medical_cats/1
  # PATCH/PUT /medical_cats/1.json
  def update
    respond_to do |format|
      if @medical_cat.update(medical_cat_params)
        format.html { redirect_to @medical_cat, notice: 'Medical cat was successfully updated.' }
        format.json { render :show, status: :ok, location: @medical_cat }
      else
        format.html { render :edit }
        format.json { render json: @medical_cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medical_cats/1
  # DELETE /medical_cats/1.json
  def destroy
    @medical_cat.destroy
    respond_to do |format|
      format.html { redirect_to medical_cats_url, notice: 'Medical cat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medical_cat
      @medical_cat = MedicalCat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def medical_cat_params
      params.require(:medical_cat).permit(:id, :date, :nature_of_emergency, :permanent, :period_year, :period_month, :hospitalized, :professional_detail_id, :created_at, :updated_at, :shape)
    end
end

app/helpers/medical_cats_helper.rb
module MedicalCatsHelper
end

app/views/medical_cats/_form.html.erb
<%= form_with(model: medical_cat, local: true) do |form| %>
  <% if medical_cat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(medical_cat.errors.count, "error") %> prohibited this medical_cat from being saved:</h2>

      <ul>
      <% medical_cat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="col-sm-6">
  <div class="field">
    <%= form.label :date, class: "control-label"  %>
    <%= form.text_field :date, class: "form-control datetimepicker" %>
  </div>
</div>

<div class="col-sm-6">
  <div class="field">
    <%= form.label :nature_of_emergency, class: "control-label"  %>
    <%= form.text_field :nature_of_emergency, class: "form-control" %>
  </div>
</div>

<div class="col-sm-6">
  <div class="field">
    <%= form.label :permanent, class: "control-label"  %>
    <%= form.check_box :permanent, class: "form-control" %>
  </div>
</div>

<div class="col-sm-6">
  <div class="field">
    <%= form.label :period_year, class: "control-label"  %>
    <%= form.number_field :period_year, class: "form-control" %>
  </div>
</div>

<div class="col-sm-6">
  <div class="field">
    <%= form.label :period_month, class: "control-label"  %>
    <%= form.number_field :period_month, class: "form-control" %>
  </div>
</div>

<div class="col-sm-6">
  <div class="field">
    <%= form.label :hospitalized, class: "control-label"  %>
    <%= form.check_box :hospitalized, class: "form-control" %>
  </div>
</div>

<div class="col-sm-6">
  <div class="field">
    <%= form.label :professional_detail_id, class: "control-label"  %>
    <%= form.select :professional_detail_id, options_from_collection_for_select(ProfessionalDetail.all, 'id', 'army_no'), {:include_blank => "Select"}, {:class=> "form-control select"} %>
  </div>
</div>

<div class="col-sm-6">
  <div class="field">
    <%= form.label :created_at, class: "control-label"  %>
    <%= form.text_field :created_at, class: "form-control datetimepicker" %>
  </div>
</div>

<div class="col-sm-6">
  <div class="field">
    <%= form.label :updated_at, class: "control-label"  %>
    <%= form.text_field :updated_at, class: "form-control datetimepicker" %>
  </div>
</div>

<div class="col-sm-6">
  <div class="field">
    <%= form.label :shape, class: "control-label"  %>
    <%= form.select :shape, options_from_collection_for_select(MasterShape.all, 'title', 'title'), {:include_blank => "Select"}, {:class=> "form-control select"} %>
  </div>
</div>

<div class="row"> 
  <div class="m-t-20 text-center">
    <%= form.submit "Save Medical Cat", class: "btn btn-primary" %>
  </div>
</div>
<% end %>

app/views/medical_cats/edit.html.erb
<div class="page-wrapper" style="margin-left: 230px !important;">
<h1>Editing Medical Cat</h1>

<%= render 'form', medical_cat: @medical_cat %>

app/views/medical_cats/index.html.erb
<div class="page-wrapper" style="margin-left: 230px !important;">
	<div class="content container-fluid">
		<div class="row">
			<div class="col-xs-4">
				<h4 class="page-title">Medical Cats</h4>
			</div>
			<div class="col-xs-8 text-right m-b-30">
				<a href="#" class="btn btn-primary pull-right rounded" data-toggle="modal" data-target="#add_medical_cat"><i class="fa fa-plus"></i> Add Medical Cats</a>
				<div class="view-icons">
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-md-12">
				<div class="table-responsive">
					<table class="table table-striped custom-table datatable">
						<thead>
							<tr>
								<th style="width:30%;">Name</th>
								<th>Army No</th>
								<th>Date</th>
								<th>Nature Of Emergency</th>
								<th>Permanent</th>
								<th>Period Year</th>
								<th>Period Month</th>
								<th>Hospitalized</th>
								<th>Professional Detail Id</th>
								<th>Created At</th>
								<th>Updated At</th>
								<th>Shape</th>
								<th class="text-right">Action</th>
							</tr>
						</thead>
						<tbody>
							<% @medical_cats.each do |medical_cat| %>
								<tr>
									<td>
										<a href="profile.html" class="avatar">J</a>
										<h2><a href="profile.html"><%= medical_cat.professional_detail.user.username %></a></h2>
									</td>
									<td><%= medical_cat.professional_detail.army_no %></td>
									<td><%= medical_cat.date %></td>
									<td><%= medical_cat.nature_of_emergency %></td>
									<td><%= medical_cat.permanent %></td>
									<td><%= medical_cat.period_year %></td>
									<td><%= medical_cat.period_month %></td>
									<td><%= medical_cat.hospitalized %></td>
									<td><%= medical_cat.professional_detail_id %></td>
									<td><%= medical_cat.created_at %></td>
									<td><%= medical_cat.updated_at %></td>
									<td><%= medical_cat.shape %></td>
									<td class="text-right">
										<div class="dropdown">
											<a href="#" class="action-icon dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-ellipsis-v"></i></a>
											<ul class="dropdown-menu pull-right">
												<li><a href="/medical_cats/<%= medical_cat.id %>/edit"><i class="fa fa-pencil m-r-5"></i> Edit</a></li>
											</ul>
										</div>
									</td>
								</tr>
							<% end %>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
<div id="add_medical_cat" class="modal custom-modal fade" role="dialog">
	<div class="modal-dialog">
		<button type="button" class="close" data-dismiss="modal">&times;</button>
		<div class="modal-content modal-lg">
			<div class="modal-header">
				<h4 class="modal-title">Add Posting Record</h4>
			</div>
			<div class="modal-body">
				<%= render 'form', medical_cat: @medical_cat %>
			</div>
		</div>
	</div>
</div>

app/views/medical_cats/new.html.erb
<h1>New Medical Cat</h1>

<%= render 'form', medical_cat: @medical_cat %>

<%= link_to 'Back', medical_cats_path %>

app/views/medical_cats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @medical_cat.id %>
</p>

<p>
  <strong>Date:</strong>
  <%= @medical_cat.date %>
</p>

<p>
  <strong>Nature of emergency:</strong>
  <%= @medical_cat.nature_of_emergency %>
</p>

<p>
  <strong>Permanent:</strong>
  <%= @medical_cat.permanent %>
</p>

<p>
  <strong>Period year:</strong>
  <%= @medical_cat.period_year %>
</p>

<p>
  <strong>Period month:</strong>
  <%= @medical_cat.period_month %>
</p>

<p>
  <strong>Hospitalized:</strong>
  <%= @medical_cat.hospitalized %>
</p>

<p>
  <strong>Professional detail:</strong>
  <%= @medical_cat.professional_detail_id %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @medical_cat.created_at %>
</p>

<p>
  <strong>Updated at:</strong>
  <%= @medical_cat.updated_at %>
</p>

<p>
  <strong>Shape:</strong>
  <%= @medical_cat.shape %>
</p>

<%= link_to 'Edit', edit_medical_cat_path(@medical_cat) %> |
<%= link_to 'Back', medical_cats_path %>