config/routes.rb
Rails.application.routes.draw do
  resources :units
  resources :homes
  resources :service_particulars
  resources :leave_records
  resources :loans
  resources :investments
  resources :posting_records
  resources :medical_cats
  resources :personel_details do
    member do
      get '/edit_more_details' => 'personel_details#edit_more_details'
      post '/update_more_details' => 'personel_details#update_more_details'
    end
  end
  resources :profiles, only: [:index, :show] do
    member do
      get '/embodiment_report' => 'profiles#embodiment_report'
      get '/embodiment_report_pdf' => 'profiles#embodiment_report', as: :embodiment_pdf_report
    end
  end
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/landing' => 'homes#landing_page'
  get '/directorate' => 'homes#directorate'
  get '/policies' => 'homes#policies'
  get '/faq' => 'homes#faq'
  get '/galary' => 'homes#galary'
  get '/news' => 'homes#news'
  get '/on_leave_index' => "homes#on_leave_index"
  get '/on_field_index' => "homes#on_field_index"
  get '/on_field_index' => "homes#on_field_index"
  get '/investments_index' => "homes#investments_index"
  get '/achievements_index' => "homes#achievements_index"

  get '/dashboard' => "homes#index"
  root to: "homes#landing_page"
  
end

app/models/personel_detail.rb
class PersonelDetail < ApplicationRecord
    has_paper_trail
    belongs_to :user
    has_one :home_address, dependent: :destroy
    has_many :family_details, dependent: :destroy
    has_many :dependent_cards, dependent: :destroy
    has_many :bank_accounts, dependent: :destroy
    has_many :investments, dependent: :destroy
    has_many :loans, dependent: :destroy
    has_many :educations, dependent: :destroy
    has_many :sports, dependent: :destroy
    has_many :achievements, dependent: :destroy
    has_many :professional_training_and_courses, dependent: :destroy

    accepts_nested_attributes_for :home_address
    accepts_nested_attributes_for :family_details
    accepts_nested_attributes_for :dependent_cards
    accepts_nested_attributes_for :bank_accounts
    accepts_nested_attributes_for :investments
    accepts_nested_attributes_for :loans
    accepts_nested_attributes_for :educations
    accepts_nested_attributes_for :sports
    accepts_nested_attributes_for :achievements
    accepts_nested_attributes_for :professional_training_and_courses

    mount_uploader :photo, PhotoUploader
    mount_uploader :family_photo, FamilyPhotoUploader


    
    def custom_label_method
        "#{army_no}"
    end
end

app/controllers/personel_details_controller.rb
class PersonelDetailsController < ApplicationController
  before_action :set_personel_detail, only: [:show, :edit, :update, :destroy, :edit_more_details, :update_more_details]

  # GET /personel_details
  # GET /personel_details.json
  def index
    @personel_details = PersonelDetail.all
    @personel_detail = PersonelDetail.new
  end

  # GET /personel_details/1
  # GET /personel_details/1.json
  def show
  end

  # GET /personel_details/new
  def new
    @personel_detail = PersonelDetail.new
  end

  # GET /personel_details/1/edit
  def edit
  end

  # POST /personel_details
  # POST /personel_details.json
  def create
    army_no = params[:personel_detail][:army_no]
    email = params[:personel_detail][:email] rescue (army_no.to_s + "@joshhr.in")
    username = params[:personel_detail][:name]
    @user = User.create!(email:  email, army_no: army_no, username: username, password: "password")
    @personel_detail = PersonelDetail.new(personel_detail_params)
    @personel_detail.user_id = @user.id
    respond_to do |format|
      if @personel_detail.save
        ProfessionalDetail.create!(user_id: @user.id, army_no: @personel_detail.army_no)
        format.html { redirect_to personel_details_url, notice: 'Personel detail was successfully created.' }
        format.json { render :show, status: :created, location: @personel_detail }
      else
        format.html { render :new }
        format.json { render json: @personel_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personel_details/1
  # PATCH/PUT /personel_details/1.json
  def update
    respond_to do |format|
      if @personel_detail.update(personel_detail_params)
        format.html { redirect_to @personel_detail, notice: 'Personel detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @personel_detail }
      else
        format.html { render :edit }
        format.json { render json: @personel_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personel_details/1
  # DELETE /personel_details/1.json
  def destroy
    @personel_detail.destroy
    respond_to do |format|
      format.html { redirect_to personel_details_url, notice: 'Personel detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def edit_more_details

  end

  def update_more_details
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_personel_detail
      @personel_detail = PersonelDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def personel_detail_params
      params.require(:personel_detail).permit(:id, :army_no, :father_name, :rank, :appointment, :name, :religion, :main_class, :sub_class, :med_cat, :mothertongue, :date_of_enrolment, :date_of_birth, :age_on_enrolment, :attestation, :date_of_attestation, :driving_license_no, :mobile_no, :adhar_no, :pancard_no, :email, :photo, :family_photo, :user_id, :created_at, :updated_at, :trade, home_address_attributes: [:id, :house_no, :street, :town, :post_office, :to_and_distance_from, :police_station, :tehsil, :district, :state, :nrs_and_distance_from_home, :_destroy], family_details_attributes: [:id, :type, :name, :relation_type, :address, :phone_number, :date_of_birth, :photo, :_destroy], bank_accounts_details: [:id, :ifsc_code, :micr_no, :bank_code, :joint, :account_number, :_destroy], educations: [:id, :degree_name, :from, :to, :institute_name, :degree_type, :_destroy])
    end
end

app/helpers/personel_details_helper.rb
module PersonelDetailsHelper
end

app/views/personel_details/_form.html.erb
<%= form_with(model: personel_detail, local: true) do |form| %>
  <div class="row">
    <% if personel_detail.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(personel_detail.errors.count, "error") %> prohibited this personel_detail from being saved:</h2>

        <ul>
        <% personel_detail.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="col-sm-6">
      <div class="form-group">
        <%= form.label :army_no, class: "control-label" %>
        <%= form.text_field :army_no, class: "form-control" %>
      </div>
    </div>

    <div class="col-sm-6">
      <div class="form-group">
        <%= form.label :father_name, class: "control-label" %>
        <%= form.text_field :father_name, class: "form-control" %>
      </div>
    </div>

    <div class="col-sm-6">
      <div class="form-group">
        <%= form.label :rank, class: "control-label" %>
        <%= form.text_field :rank, class: "form-control" %>
      </div>
    </div>

    <div class="col-sm-6">
      <div class="form-group">
        <%= form.label :appointment, class: "control-label" %>
        <%= form.text_field :appointment, class: "form-control" %>
      </div>
    </div>

    <div class="col-sm-6">
      <div class="form-group">
        <%= form.label :name, class: "control-label" %>
        <%= form.text_field :name, class: "form-control" %>
      </div>
    </div>

    <div class="col-sm-6">
      <div class="form-group">
        <%= form.label :religion, class: "control-label" %>
        <%= form.text_field :religion, class: "form-control" %>
      </div>
    </div>

    <div class="col-sm-6">
      <div class="form-group">
        <%= form.label :main_class, class: "control-label" %>
        <%= form.text_field :main_class, class: "form-control" %>
      </div>
    </div>

    <div class="col-sm-6">
      <div class="form-group">
        <%= form.label :sub_class, class: "control-label" %>
        <%= form.text_field :sub_class, class: "form-control" %>
      </div>
    </div>

    <div class="col-sm-6">
      <div class="form-group">
        <%= form.label :med_cat, class: "control-label" %>
        <%= form.text_field :med_cat, class: "form-control" %>
      </div>
    </div>

    <div class="col-sm-6">
      <div class="form-group">
        <%= form.label :mothertongue, class: "control-label" %>
        <%= form.text_field :mothertongue, class: "form-control" %>
      </div>
    </div>

    <div class="col-sm-6">
      <div class="form-group">
        <%= form.label :date_of_enrolment, class: "control-label" %>
        <%= form.text_field :date_of_enrolment, class: "form-control datetimepicker" %>
      </div>
    </div>

    <div class="col-sm-6">
      <div class="form-group">
        <%= form.label :date_of_birth, class: "control-label" %>
        <%= form.text_field :date_of_birth, class: "form-control datetimepicker" %>
      </div>
    </div>

    <div class="col-sm-6">
      <div class="form-group">
        <%= form.label :age_on_enrolment, class: "control-label" %>
        <%= form.text_field :age_on_enrolment, class: "form-control" %>
      </div>
    </div>

    <div class="col-sm-6">
      <div class="form-group">
        <%= form.label :attestation, class: "control-label" %>
        <%= form.text_field :attestation, class: "form-control" %>
      </div>
    </div>

    <div class="col-sm-6">
      <div class="form-group">
        <%= form.label :date_of_attestation, class: "control-label" %>
        <%= form.text_field :date_of_attestation, class: "form-control datetimepicker" %>
      </div>
    </div>

    <div class="col-sm-6">
      <div class="form-group">
        <%= form.label :driving_license_no, class: "control-label" %>
        <%= form.text_field :driving_license_no, class: "form-control" %>
      </div>
    </div>

    <div class="col-sm-6">
      <div class="form-group">
        <%= form.label :mobile_no, class: "control-label" %>
        <%= form.text_field :mobile_no, class: "form-control" %>
      </div>
    </div>

    <div class="col-sm-6">
      <div class="form-group">
        <%= form.label :adhar_no, class: "control-label" %>
        <%= form.text_field :adhar_no, class: "form-control" %>
      </div>
    </div>

    <div class="col-sm-6">
      <div class="form-group">
        <%= form.label :pancard_no, class: "control-label" %>
        <%= form.text_field :pancard_no, class: "form-control" %>
      </div>
    </div>

    <div class="col-sm-6">
      <div class="form-group">
        <%= form.label :email, class: "control-label" %>
        <%= form.text_field :email, class: "form-control" %>
      </div>
    </div>

    <div class="col-sm-6">
      <div class="form-group">
        <%= form.label :photo, class: "control-label" %>
        <%= form.file_field :photo, class: "form-control" %>
      </div>
    </div>

    <div class="col-sm-6">
      <div class="form-group">
        <%= form.label :family_photo, class: "control-label" %>
        <%= form.file_field :family_photo, class: "form-control" %>
      </div>
    </div>

    <div class="col-sm-6">
      <div class="form-group">
        <%= form.label :trade, class: "control-label" %>
        <%= form.text_field :trade, class: "form-control" %>
      </div>
    </div>
    <div class="row"> 
      <div class="m-t-20 text-center">
        <%= form.submit "Save JCO's/OR's", class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/personel_details/edit.html.erb
<div class="page-wrapper" style="margin-left: 230px !important;">
    <%= render 'form', personel_detail: @personel_detail %>
</div>

<%= link_to 'Show', @personel_detail %> |
<%= link_to 'Back', personel_details_path %>

app/views/personel_details/index.html.erb
<div class="page-wrapper" style="margin-left: 230px !important;">
	<div class="content container-fluid">
		<div class="row">
			<div class="col-xs-4">
				<h4 class="page-title">JCO's/OR's</h4>
			</div>
			<div class="col-xs-8 text-right m-b-30">
				<a href="#" class="btn btn-primary pull-right rounded" data-toggle="modal" data-target="#add_employee"><i class="fa fa-plus"></i> Add JCO's/OR's</a>
				<div class="view-icons">
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-md-12">
				<div class="table-responsive">
					<table class="table table-striped custom-table datatable">
						<thead>
							<tr>
								<th style="width:30%;">Name</th>
								<th>Army No</th>
								<th>Email</th>
								<th>Mobile</th>
								<th>Date of enrolment</th>
								<th>Rank</th>
								<th class="text-right">Action</th>
							</tr>
						</thead>
						<tbody>
							<% @personel_details.each do |personel_detail| %>
								<tr>
									<td>
										<a href="profile.html" class="avatar">J</a>
										<h2><a href="profile.html"><%= personel_detail.name %> <span><%= personel_detail.rank %></span></a></h2>
									</td>
									<td><%= personel_detail.army_no %></td>
									<td><%= personel_detail.email %></td>
									<td><%= personel_detail.mobile_no %></td>
									<td><%= personel_detail.date_of_enrolment %></td>
									<td>
										<%= personel_detail.rank %>
									</td>
									<td class="text-right">
										<div class="dropdown">
											<a href="#" class="action-icon dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-ellipsis-v"></i></a>
											<ul class="dropdown-menu pull-right">
												<li><a href="/personel_details/<%= personel_detail.id %>/edit"><i class="fa fa-pencil m-r-5"></i> Edit</a></li>
												<li>
													<a href="/personel_details/<%= personel_detail.id %>/edit_more_details"><i class="fa fa-pencil m-r-5"></i> Add More Details</a>
													<!-- <a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/personel_details/<%#= personel_detail.id %>">Destroy</a> -->
												</li>
											</ul>
										</div>
									</td>
								</tr>
							<% end %>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
<div id="add_employee" class="modal custom-modal fade" role="dialog">
	<div class="modal-dialog">
		<button type="button" class="close" data-dismiss="modal">&times;</button>
		<div class="modal-content modal-lg">
			<div class="modal-header">
				<h4 class="modal-title">Add Employee</h4>
			</div>
			<div class="modal-body">
				<%= render 'form', personel_detail: @personel_detail %>
			</div>
		</div>
	</div>
</div>

app/views/personel_details/new.html.erb
<h1>New Personel Detail</h1>

<%= render 'form', personel_detail: @personel_detail %>

<%= link_to 'Back', personel_details_path %>

app/views/personel_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @personel_detail.id %>
</p>

<p>
  <strong>Army no:</strong>
  <%= @personel_detail.army_no %>
</p>

<p>
  <strong>Father name:</strong>
  <%= @personel_detail.father_name %>
</p>

<p>
  <strong>Rank:</strong>
  <%= @personel_detail.rank %>
</p>

<p>
  <strong>Appointment:</strong>
  <%= @personel_detail.appointment %>
</p>

<p>
  <strong>Name:</strong>
  <%= @personel_detail.name %>
</p>

<p>
  <strong>Religion:</strong>
  <%= @personel_detail.religion %>
</p>

<p>
  <strong>Main class:</strong>
  <%= @personel_detail.main_class %>
</p>

<p>
  <strong>Sub class:</strong>
  <%= @personel_detail.sub_class %>
</p>

<p>
  <strong>Med cat:</strong>
  <%= @personel_detail.med_cat %>
</p>

<p>
  <strong>Mothertongue:</strong>
  <%= @personel_detail.mothertongue %>
</p>

<p>
  <strong>Date of enrolment:</strong>
  <%= @personel_detail.date_of_enrolment %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%= @personel_detail.date_of_birth %>
</p>

<p>
  <strong>Age on enrolment:</strong>
  <%= @personel_detail.age_on_enrolment %>
</p>

<p>
  <strong>Attestation:</strong>
  <%= @personel_detail.attestation %>
</p>

<p>
  <strong>Date of attestation:</strong>
  <%= @personel_detail.date_of_attestation %>
</p>

<p>
  <strong>Driving license no:</strong>
  <%= @personel_detail.driving_license_no %>
</p>

<p>
  <strong>Mobile no:</strong>
  <%= @personel_detail.mobile_no %>
</p>

<p>
  <strong>Adhar no:</strong>
  <%= @personel_detail.adhar_no %>
</p>

<p>
  <strong>Pancard no:</strong>
  <%= @personel_detail.pancard_no %>
</p>

<p>
  <strong>Email:</strong>
  <%= @personel_detail.email %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @personel_detail.photo %>
</p>

<p>
  <strong>Family photo:</strong>
  <%= @personel_detail.family_photo %>
</p>

<p>
  <strong>User:</strong>
  <%= @personel_detail.user_id %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @personel_detail.created_at %>
</p>

<p>
  <strong>Updated at:</strong>
  <%= @personel_detail.updated_at %>
</p>

<p>
  <strong>Trade:</strong>
  <%= @personel_detail.trade %>
</p>

<%= link_to 'Edit', edit_personel_detail_path(@personel_detail) %> |
<%= link_to 'Back', personel_details_path %>