config/routes.rb
Rails.application.routes.draw do
  resources :units
  resources :homes
  resources :service_particulars
  resources :leave_records
  resources :loans
  resources :investments
  resources :posting_records
  resources :medical_cats
  resources :personel_details do
    member do
      get '/edit_more_details' => 'personel_details#edit_more_details'
      post '/update_more_details' => 'personel_details#update_more_details'
    end
  end
  resources :profiles, only: [:index, :show] do
    member do
      get '/embodiment_report' => 'profiles#embodiment_report'
      get '/embodiment_report_pdf' => 'profiles#embodiment_report', as: :embodiment_pdf_report
    end
  end
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/landing' => 'homes#landing_page'
  get '/directorate' => 'homes#directorate'
  get '/policies' => 'homes#policies'
  get '/faq' => 'homes#faq'
  get '/galary' => 'homes#galary'
  get '/news' => 'homes#news'
  get '/on_leave_index' => "homes#on_leave_index"
  get '/on_field_index' => "homes#on_field_index"
  get '/on_field_index' => "homes#on_field_index"
  get '/investments_index' => "homes#investments_index"
  get '/achievements_index' => "homes#achievements_index"

  get '/dashboard' => "homes#index"
  root to: "homes#landing_page"
  
end

app/models/unit.rb
class Unit < ApplicationRecord
    has_paper_trail
    has_many :unit_galleries, dependent: :destroy
    has_many :commanding_officers, dependent: :destroy
    has_many :battle_honors, dependent: :destroy
    has_many :notable_people, dependent: :destroy
    has_many :champions, dependent: :destroy

    accepts_nested_attributes_for :unit_galleries
    accepts_nested_attributes_for :commanding_officers
    accepts_nested_attributes_for :battle_honors
    accepts_nested_attributes_for :notable_people
    accepts_nested_attributes_for :champions

    mount_uploader :unit_logo, PhotoUploader
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :set_unit, only: [:show, :edit, :update, :destroy]

  # GET /units
  # GET /units.json
  def index
    @units = Unit.all
  end

  # GET /units/1
  # GET /units/1.json
  def show
    render layout: false
  end

  # GET /units/new
  def new
    @unit = Unit.new
  end

  # GET /units/1/edit
  def edit
  end

  # POST /units
  # POST /units.json
  def create
    @unit = Unit.new(unit_params)

    respond_to do |format|
      if @unit.save
        format.html { redirect_to @unit, notice: 'Unit was successfully created.' }
        format.json { render :show, status: :created, location: @unit }
      else
        format.html { render :new }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /units/1
  # PATCH/PUT /units/1.json
  def update
    respond_to do |format|
      if @unit.update(unit_params)
        format.html { redirect_to @unit, notice: 'Unit was successfully updated.' }
        format.json { render :show, status: :ok, location: @unit }
      else
        format.html { render :edit }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    @unit.destroy
    respond_to do |format|
      format.html { redirect_to units_url, notice: 'Unit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unit_params
      params.require(:unit).permit(:name, :history)
    end
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/units/_form.html.erb
<%= form_with(model: unit, local: true) do |form| %>
  <% if unit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(unit.errors.count, "error") %> prohibited this unit from being saved:</h2>

      <ul>
      <% unit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :history %>
    <%= form.text_area :history %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/units/edit.html.erb
<h1>Editing Unit</h1>

<%= render 'form', unit: @unit %>

<%= link_to 'Show', @unit %> |
<%= link_to 'Back', units_path %>

app/views/units/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Units</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>History</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @units.each do |unit| %>
      <tr>
        <td><%= unit.name %></td>
        <td><%= unit.history %></td>
        <td><%= link_to 'Show', unit %></td>
        <td><%= link_to 'Edit', edit_unit_path(unit) %></td>
        <td><%= link_to 'Destroy', unit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Unit', new_unit_path %>

app/views/units/new.html.erb
<h1>New Unit</h1>

<%= render 'form', unit: @unit %>

<%= link_to 'Back', units_path %>

app/views/units/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<title>Soldiers life</title>
<meta charset="utf-8">    
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<script src="../cdn-cgi/apps/head/3ts2ksMwXvKRuG480KNifJ2_JNM.js"></script><link rel="icon" href="/landing_page/img/favicon.ico" type="image/x-icon">
<link rel="shortcut icon" href="/landing_page/img/favicon.ico" type="image/x-icon" />
<meta name="description" content="Your description">
<meta name="keywords" content="Your keywords">
<meta name="author" content="Your name">
<!--CSS-->
<link rel="stylesheet" href="/landing_page/css/bootstrap.css" >
<link rel="stylesheet" href="/landing_page/css/style.css">
<link rel="stylesheet" href="/landing_page/css/touchTouch.css">
<link rel="stylesheet" href="fonts/font-awesome.css">
<!--JS-->
<script src="/landing_page/js/jquery.js"></script>
<script src="/landing_page/js/jquery-migrate-1.2.1.min.js"></script>
<script src="/landing_page/js/superfish.js"></script>
<script src="/landing_page/js/jquery.easing.1.3.js"></script>
<script src="/landing_page/js/jquery.mobilemenu.js"></script>
<script src="/landing_page/js/jquery.equalheights.js"></script> 
<script src="/landing_page/js/jquery.ui.totop.js"></script>
<script src="/landing_page/js/touchTouch.jquery.js"></script>
<script>
   $(window).load(function() {
     // Initialize the gallery
    $('.trainerBox figure a').touchTouch();
  });
</script>
<!--[if lt IE 9]>
    <div style='text-align:center'><a href="http://windows.microsoft.com/en-US/internet-explorer/products/ie/home?ocid=ie6_countdown_bannercode"><img src="http://storage.ie6countdown.com/assets/100/images/banners/warning_bar_0000_us.jpg" border="0" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today." /></a></div>  
  <![endif]-->
  <!--[if lt IE 9]><script src="../docs-assets//landing_page/js/ie8-responsive-file-warning.js"></script><![endif]-->

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond./landing_page/js/1.3.0/respond.min.js"></script>
  <![endif]-->
  <style>
    .block-with-text {
      overflow: hidden;
      display: -webkit-box;
      -webkit-line-clamp: 3;
      -webkit-box-orient: vertical; 
    }
  </style>
</head>
<body>
<!--header-->
<div class="main">
<header>
    <div class="container">
        <div class="row">
            <article class="col-lg-12 col-md-12 col-sm-12">
                <h1 class="navbar-brand navbar-brand_"><a href="index.html"><img src="/landing_page/img/logo.gif" alt="" style="width:25%;"></a></h1>
                <div class="menuBox clearfix">
                    <nav class="navbar navbar-default navbar-static-top tm_navbar clearfix" role="navigation">
                            <ul class="nav sf-menu clearfix">
                                <li class="active"><a href="/landing">Home</a></li>
                                <li class="sub-menu"><a href="#">About<span></span></a>
                                    <ul class="submenu">
                        				<li><a href="/directorate">Directorate</a></li>
                        				<li>
                                            <a href="index.html#">Unit</a>
                                            <ul class="submenu">
                                                <li><a href="/units/1">111 Kumaon</a></li>
                                                <li><a href="/units/1">150 Punjab</a></li>
                                                <li><a href="/units/1">174 Engineers</a></li>
                                            </ul>
                                        </li>
                        			</ul>
                                </li>
                                <li><a href="/landing_page/index-2.html">TA Policies</a></li>
                                <li><a href="/landing_page/index-3.html">Gallery</a></li>
                                <li><a href="/landing_page/index-4.html">News</a></li>
                                <li><a href="/landing_page/index-5.html">FAQ</a></li>
                                <li><a href="/users/sign_in">Login</a></li>
                            </ul>
                        </nav>
                </div>
            </article>
        </div>
    </div>
</header>
<section class="sub_pic">
    <figure><img src="/landing_page/img/sub_pic.jpg" alt=""></figure>
</section>
<div class="global indent">
    <!--content-->
    <div class="container">
        <div class="row">
            <article class="col-lg-6 col-md-6 col-sm-12 who-box">
                <h3>Unit Galary</h3>
                <div class="thumb-pad4">
                    <div class="thumbnail">
                        <figure><img src="<%= @unit.unit_galleries.last.photo.url %>" alt=""></figure>
                        <div class="caption">
                            <h5><%= @unit.unit_galleries.last.caption %></h5>
                            <p>Sed eu augue quam. Nunc sollicitudin lacinia justo sed ornare. Nunc semper bibendum magna, vel ornare lorem porttitor sed. Sed faucibus tellus vitae eros congue.</p>
                            <p>Sed eu augue quam. Nunc sollicitudin lacinia justo sed ornare. Nunc semper bibendum magna, vel ornare lorem porttitor sed. Sed faucibus tellus vitae eros congue.</p>
                            <a href="index-1.html#" class="btn-default btn1">More info</a>
                        </div>
                    </div>
                </div>
            </article>
            
            <article class="col-lg-6 col-md-6 col-sm-12 trainers-box">
                <h3>History</h3>
                <h5>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Praesent vestibulum.</h5>
                <p><%= @unit.history %></p>
                
            </article>
        </div>
        <div class="row">
          <article class="col-lg-6 col-md-6 col-sm-12 history-box">
                <h3>Notable Achievements</h3>
                <ul class="list6">
                  <% @unit.notable_people.each_with_index.each do |bh, index| %>
                    <li>
                      <div class="badge"><%= index + 1%></div>
                      <div class="extra-wrap">
                          <h5><%= bh.person_name %></h5>
                          <p><%= bh.description %></p>
                      </div>
                    </li>
                  <% end %>
                </ul>
            </article>
            <article class="col-lg-6 col-md-6 col-sm-12 history-box">
                <h3>Battle Honors and distiguished services</h3>
                <ul class="list6">
                    <% @unit.battle_honors.each_with_index.each do |bh, index| %>
                      <li>
                        <div class="badge"><%= index + 1%></div>
                        <div class="extra-wrap">
                            <h5><%= bh.title %></h5>
                            <p><%= bh.description %></p>
                        </div>
                      </li>
                    <% end %>
                    
                </ul>
            </article>
        </div>
    </div>
    <section class="testimBox"> 
        <div class="container">
            <hr>
            <h3>Our Team</h3>
            <div class="row">
              <% @unit.commanding_officers.each do |co|%>
                <article class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
                    <div class="thumb-pad3">
                        <div class="thumbnail maxheight">
                            <figure><img src="<%= co.photo.url %>" alt=""></figure>
                            <div class="caption">
                                <a href="index-1.html#"><%= co.name %></a>
                                <p><%= co.designation %></p>
                            </div>
                        </div>
                    </div>
                </article>
              <% end %>
            </div>
        </div>
    </section>
        <section class="testimBox"> 
        <div class="container">
            <hr>
            <h3>Champions</h3>
            <div class="row">
              <% @unit.champions.each do |ch| %>
                <article class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
                    <div class="thumb-pad3">
                        <div class="thumbnail maxheight">
                            <figure><img src="<%= ch.photo.url %>" alt=""></figure>
                            <div class="caption">
                                <a href="index-1.html#"><%= ch.champ_name %></a>
                                <p class="block-with-text"><%= ch.description %></p>
                            </div>
                        </div>
                    </div>
                </article>
              <% end %>
            </div>
        </div>
    </section>
</div>
</div>
<!--footer-->
<footer>
    <hr>
    <div class="container">
        <div class="row">
            <article class="col-lg-12 col-md-12 col-sm-12">
                <figure><img src="<%= @unit.unit_logo.url%>" alt=""></figure>
                <p>&copy; <em id="copyright-year"></em> | <a href="index-6.html">Privacy Policy</a></p>
            </article>
        </div>
    </div>
</footer>
<script src="/landing_page/js/bootstrap.min.js"></script>
<script src="/landing_page/js/tm-scripts.js"></script>
</body>
</html>