config/routes.rb
Rails.application.routes.draw do
  resources :units
  resources :homes
  resources :service_particulars
  resources :leave_records
  resources :loans
  resources :investments
  resources :posting_records
  resources :medical_cats
  resources :personel_details do
    member do
      get '/edit_more_details' => 'personel_details#edit_more_details'
      post '/update_more_details' => 'personel_details#update_more_details'
    end
  end
  resources :profiles, only: [:index, :show] do
    member do
      get '/embodiment_report' => 'profiles#embodiment_report'
      get '/embodiment_report_pdf' => 'profiles#embodiment_report', as: :embodiment_pdf_report
    end
  end
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/landing' => 'homes#landing_page'
  get '/directorate' => 'homes#directorate'
  get '/policies' => 'homes#policies'
  get '/faq' => 'homes#faq'
  get '/galary' => 'homes#galary'
  get '/news' => 'homes#news'
  get '/on_leave_index' => "homes#on_leave_index"
  get '/on_field_index' => "homes#on_field_index"
  get '/on_field_index' => "homes#on_field_index"
  get '/investments_index' => "homes#investments_index"
  get '/achievements_index' => "homes#achievements_index"

  get '/dashboard' => "homes#index"
  root to: "homes#landing_page"
  
end

app/models/posting_record.rb
class PostingRecord < ApplicationRecord
    has_paper_trail
    belongs_to :professional_detail
end

app/controllers/posting_records_controller.rb
class PostingRecordsController < ApplicationController
  before_action :set_posting_record, only: [:show, :edit, :update, :destroy]

  # GET /posting_records
  # GET /posting_records.json
  def index
    @posting_records = PostingRecord.all
    @posting_record = PostingRecord.new
  end

  # GET /posting_records/1
  # GET /posting_records/1.json
  def show
  end

  # GET /posting_records/new
  def new
    @posting_record = PostingRecord.new
  end

  # GET /posting_records/1/edit
  def edit
  end

  # POST /posting_records
  # POST /posting_records.json
  def create
    @posting_record = PostingRecord.new(posting_record_params)

    respond_to do |format|
      if @posting_record.save
        format.html { redirect_to @posting_record, notice: 'Posting record was successfully created.' }
        format.json { render :show, status: :created, location: @posting_record }
      else
        format.html { render :new }
        format.json { render json: @posting_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posting_records/1
  # PATCH/PUT /posting_records/1.json
  def update
    respond_to do |format|
      if @posting_record.update(posting_record_params)
        format.html { redirect_to @posting_record, notice: 'Posting record was successfully updated.' }
        format.json { render :show, status: :ok, location: @posting_record }
      else
        format.html { render :edit }
        format.json { render json: @posting_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posting_records/1
  # DELETE /posting_records/1.json
  def destroy
    @posting_record.destroy
    respond_to do |format|
      format.html { redirect_to posting_records_url, notice: 'Posting record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_posting_record
      @posting_record = PostingRecord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def posting_record_params
      params.require(:posting_record).permit(:id, :from, :to, :peace_duty, :field_dduty, :total_peace_duty_day, :total_field_duty_day, :professional_detail_id, :created_at, :updated_at)
    end
end

app/helpers/posting_records_helper.rb
module PostingRecordsHelper
end

app/views/posting_records/_form.html.erb
<%= form_with(model: posting_record, local: true) do |form| %>
  <% if posting_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(posting_record.errors.count, "error") %> prohibited this posting_record from being saved:</h2>

      <ul>
      <% posting_record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="col-sm-6">
  <div class="field">
    <%= form.label :from, class: "control-label"   %>
    <%= form.text_field :from, class: "form-control datetimepicker" %>
  </div>
</div>

<div class="col-sm-6">
  <div class="field">
    <%= form.label :to, class: "control-label"   %>
    <%= form.text_field :to, class: "form-control datetimepicker" %>
  </div>
</div>

<div class="col-sm-6">
  <div class="field">
    <%= form.label :peace_duty, class: "control-label"   %>
    <%= form.check_box :peace_duty, class: "form-control" %>
  </div>
</div>

<div class="col-sm-6">
  <div class="field">
    <%= form.label :field_dduty, class: "control-label"   %>
    <%= form.check_box :field_dduty, class: "form-control" %>
  </div>
</div>

<div class="col-sm-6">
  <div class="field">
    <%= form.label :total_peace_duty_day, class: "control-label"   %>
    <%= form.number_field :total_peace_duty_day, class: "form-control" %>
  </div>
</div>

<div class="col-sm-6">
  <div class="field">
    <%= form.label :total_field_duty_day, class: "control-label"   %>
    <%= form.number_field :total_field_duty_day, class: "form-control" %>
  </div>
</div>

<div class="col-sm-6">
  <div class="field">
    <%= form.label :professional_detail_id, class: "control-label"   %>
    <%= form.select :professional_detail_id, options_from_collection_for_select(ProfessionalDetail.all, 'id', 'army_no'), {:include_blank => "Select"}, {:class=> "form-control select"} %>
  </div>
</div>

 <div class="row"> 
  <div class="m-t-20 text-center">
    <%= form.submit "Save Posting Record", class: "btn btn-primary" %>
  </div>
</div>
<% end %>

app/views/posting_records/edit.html.erb
<div class="page-wrapper" style="margin-left: 230px !important;">
<h1>Editing Posting Record</h1>

<%= render 'form', posting_record: @posting_record %>

app/views/posting_records/index.html.erb
<div class="page-wrapper" style="margin-left: 230px !important;">
	<div class="content container-fluid">
		<div class="row">
			<div class="col-xs-4">
				<h4 class="page-title">Posting Records</h4>
			</div>
			<div class="col-xs-8 text-right m-b-30">
				<a href="#" class="btn btn-primary pull-right rounded" data-toggle="modal" data-target="#add_posting_record"><i class="fa fa-plus"></i> Add Posting Records</a>
				<div class="view-icons">
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-md-12">
				<div class="table-responsive">
					<table class="table table-striped custom-table datatable">
						<thead>
							<tr>
								<th style="width:30%;">Name</th>
								<th>Army No</th>
								<th>From</th>
								<th>To</th>
								<th>Peace Duty</th>
								<th>Field Duty</th>
								<th>Total Peace Duty Day</th>
                				<th>Total Field Duty Day</th>
								<th class="text-right">Action</th>
							</tr>
						</thead>
						<tbody>
							<% @posting_records.each do |posting_record| %>
								<tr>
									<td>
										<a href="profile.html" class="avatar">J</a>
										<h2><a href="profile.html"><%= posting_record.professional_detail.user.username %></a></h2>
									</td>
									<td><%= posting_record.professional_detail.army_no %></td>
									<td><%= posting_record.from %></td>
									<td><%= posting_record.to %></td>
									<td><%= posting_record.peace_duty %></td>
									<td><%= posting_record.field_dduty %></td>
									<td><%= posting_record.total_peace_duty_day %></td>
                  					<td><%= posting_record.total_field_duty_day %></td>
									<td class="text-right">
										<div class="dropdown">
											<a href="#" class="action-icon dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-ellipsis-v"></i></a>
											<ul class="dropdown-menu pull-right">
												<li><a href="/posting_records/<%= posting_record.id %>/edit"><i class="fa fa-pencil m-r-5"></i> Edit</a></li>
											</ul>
										</div>
									</td>
								</tr>
							<% end %>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
<div id="add_posting_record" class="modal custom-modal fade" role="dialog">
	<div class="modal-dialog">
		<button type="button" class="close" data-dismiss="modal">&times;</button>
		<div class="modal-content modal-lg">
			<div class="modal-header">
				<h4 class="modal-title">Add Posting Record</h4>
			</div>
			<div class="modal-body">
				<%= render 'form', posting_record: @posting_record %>
			</div>
		</div>
	</div>
</div>

app/views/posting_records/new.html.erb
<h1>New Posting Record</h1>

<%= render 'form', posting_record: @posting_record %>

<%= link_to 'Back', posting_records_path %>

app/views/posting_records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @posting_record.id %>
</p>

<p>
  <strong>From:</strong>
  <%= @posting_record.from %>
</p>

<p>
  <strong>To:</strong>
  <%= @posting_record.to %>
</p>

<p>
  <strong>Peace duty:</strong>
  <%= @posting_record.peace_duty %>
</p>

<p>
  <strong>Field dduty:</strong>
  <%= @posting_record.field_dduty %>
</p>

<p>
  <strong>Total peace duty day:</strong>
  <%= @posting_record.total_peace_duty_day %>
</p>

<p>
  <strong>Total field duty day:</strong>
  <%= @posting_record.total_field_duty_day %>
</p>

<p>
  <strong>Professional detail:</strong>
  <%= @posting_record.professional_detail_id %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @posting_record.created_at %>
</p>

<p>
  <strong>Updated at:</strong>
  <%= @posting_record.updated_at %>
</p>

<%= link_to 'Edit', edit_posting_record_path(@posting_record) %> |
<%= link_to 'Back', posting_records_path %>